config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # namespace :adminの中に書いているので、/admin/users/new のように /admin から始まるようになる。
  # ヘルパーメソッドも「admin_」がつくようになる
  namespace :admin do
    resources :users
  end
  # http://localhost:3000 にアクセスした時はタスク一覧を表示する
  root to: 'tasks#index'
  # resorce :コントローラー名 でCRUDのルーティングを一括で設定
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # 「bcrypt」というgemのメソッドが「has_secure_password」
  # has_secure_passwordを使う場合は、テーブルのカラム名は「password_digest」にする
  # ユーザーが入力したパスワードは「has_secure_password」メソッドによって暗号化（ハッシュ化）されてカラムに保存される
  # ハッシュかされたパスワードは不可逆的な変換なので元に戻すことはできない
  # しかし、同じパスワードからは同じハッシュ化したパスワードが生成されるので、ログインする際にパスワードが一致しているかどうかの判定に使える。
  # またDBに不正アクセスされてパスワードが盗まれても無意味で、不可逆的なので安心
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  # 「関連」というDB上の紐付けを前提にモデルクラス同士を紐ずける。
  # UserモデルとTaksモデルは「１対多数」なので、1の方に「has_many :多数のモデル名」を指定
  # has_manyはUserクラスのidカラムを、外部キーとして持つTaskクラスがあり、Userクラスのidカラムを複数登録可能であることを表す。
  # こうすると、Userクラスのインスタンスに対して「user.tasks」メソッドで紐付いたTaskオブジェクトの一覧（ユーザーが登録したタスクの一覧）を取得できる
  has_many :tasks
end

app/controllers/admin/users_controller.rb
# Adminというモジュール（名前空間）のなかの「UsersController」という意味
class Admin::UsersController < ApplicationController
  # ユーザーを操作する系のアクションが実行される前に「require_admin」メソッドを実行する
  before_action :require_admin

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  # StrongParamerters
  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  # 管理者権限ない人はリダイレクトする
  def require_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message


/ form_withの引数に[:admin, user]を渡すとuserの中身を見て「/admin/users」というurlをRailsが生成してくれます。
= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  / パスワードを２回入力してもらって、ユーザーの打ち間違いでログインできなくなるのを防ぐ
  / passwordとpassword_confirmationの値が一致しないとバリデーション失敗する(自動で検証してくれる)
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
  = link_to  "一覧", admin_users_path, class: 'nav-link'

= render partial: "form", locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to  "新規登録", new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
    tbody
      - @user.each do |user|
        tr
          / [:admin]が/admin を作る。[user]が /users/id のようにuserの中身をみて適切なURLを生成してくれる。
          td= link_to  user.name, [:admin, user]
          td= user.email
          td= user.admin? ? 'あり' : 'なし'
          td= user.created_at
          td= user.updated_at
          td
            = link_to  "編集", edit_admin_user_path(user), class: 'btn btn-primary mr-3'
            / [:admin]が /admin を表す。[user]が /user/id をuserの中身を見て適切に作ってくれる。なので「/admin/users/:id」になる
            = link_to  "削除", [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいいですか？"}, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  = link_to  "一覧", admin_users_path, class: 'nav-link'

= render partial: "form", locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-end
  = link_to  "一覧", admin_users_path, class: 'nav-link'

table.table.table-hover
  tbody
    tr
      / [:admin]が/admin を作る。[user]が /users/id のようにuserの中身をみて適切なURLを生成してくれる。
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to  "編集", edit_admin_user_path, class: 'btn btn-primary mr-3'
/ [:admin]が /admin を表す。[user]が /user/id をuserの中身を見て適切に作ってくれる。なので「/admin/users/:id」になる
= link_to  "削除", [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいいですか？" }, class: 'btn btn-danger'