config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # namespace :adminの中に書いているので、/admin/users/new のように /admin から始まるようになる。
  # ヘルパーメソッドも「admin_」がつくようになる
  namespace :admin do
    resources :users
  end
  # http://localhost:3000 にアクセスした時はタスク一覧を表示する
  root to: 'tasks#index'
  # resorce :コントローラー名 でCRUDのルーティングを一括で設定
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Taskleaf
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Taskleaf

      ul.navbar-nav.ml-auto
        / application_controllerに記載したヘルパーメソッドを呼んでいる
        - if current_user
          li.nav-item.nav-link= "ログインユーザー：#{current_user.name}"
          li.nav-item= link_to 'タスク一覧', tasks_path, class: 'nav-link'
          / 管理者権限があるかどうかでリンクの表示・非表示を返る
          - if current_user.admin?
            li.nav-item= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'

    .container
      / フラッシュメッセージを表示。リロードすると消える。
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield